from typing import Dict, Any, List
from html import escape

def _nav(pages: List[Dict[str, Any]]) -> str:
    items = []
    for p in pages:
        label = escape(p.get("title", ""))
        href = escape(p.get("slug", "/"))
        items.append(f'<a href="{href}">{label}</a>')
    return '<nav class="nav">' + " | ".join(items) + "</nav>"

def _hero(site: Dict[str, Any], hero: Dict[str, Any], page: Dict[str, Any]) -> str:
    brand = escape(site.get("brand", ""))
    headline = escape(hero.get("headline", ""))
    subhead = escape(hero.get("subhead", ""))
    title = escape(page.get("title", ""))
    return f"""<header class="hero">
  <div class="brand">{brand}</div>
  <h1>{title}</h1>
  <div class="headline">{headline}</div>
  <p class="subhead">{subhead}</p>
</header>
""".strip()

def _features(features: List[Dict[str, Any]]) -> str:
    if not features:
        return ""
    cards = []
    for f in features:
        cards.append(
            f'<div class="card"><div class="card-title">{escape(f.get("title",""))}</div>'
            f'<div class="card-desc">{escape(f.get("desc",""))}</div></div>'
        )
    return '<section><h2>What You Get</h2><div class="grid">' + "".join(cards) + "</div></section>"

def _pillars(pillars: List[Dict[str, Any]]) -> str:
    if not pillars:
        return ""
    blocks = []
    for p in pillars:
        bullets = "".join([f"<li>{escape(b)}</li>" for b in (p.get("bullets") or [])])
        blocks.append(f'<div class="pillar"><h3>{escape(p.get("title",""))}</h3><ul>{bullets}</ul></div>')
    return '<section><h2>Customer-Centric Pillars</h2>' + "".join(blocks) + "</section>"

def _offers(offers: Dict[str, Any]) -> str:
    if not offers:
        return ""
    parts = []
    for key in ["workshop", "vflp"]:
        o = offers.get(key) or {}
        if not o:
            continue
        parts.append(
            f'<div class="offer"><div class="offer-title">{escape(o.get("title",""))}</div>'
            f'<a class="btn" href="{escape(o.get("cta_href","/"))}">{escape(o.get("cta_label","Learn More"))}</a></div>'
        )
    return '<section><h2>Next Steps</h2><div class="grid">' + "".join(parts) + "</div></section>"

def render_page(site: Dict[str, Any], doc: Dict[str, Any], page: Dict[str, Any]) -> str:
    pages = doc.get("pages") or []
    hero = doc.get("hero") or {}

    sections_html = []
    for s in (page.get("sections") or []):
        t = s.get("type")
        if t == "hero":
            sections_html.append(_hero(site, hero, page))
        elif t == "features":
            sections_html.append(_features(doc.get("features") or []))
        elif t == "pillars":
            sections_html.append(_pillars(doc.get("pillars") or []))
        elif t == "offers":
            sections_html.append(_offers(doc.get("offers") or {}))

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>{escape(page.get("title",""))}</title>
  <style>
    body{{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial; margin:0; padding:0; line-height:1.45;}}
    .wrap{{max-width:980px; margin:0 auto; padding:24px;}}
    .nav a{{text-decoration:none; color:#111;}}
    .hero{{padding:16px 0 8px;}}
    .brand{{font-weight:700; opacity:.75;}}
    .headline{{font-size:18px; font-weight:650; margin-top:8px;}}
    .subhead{{opacity:.85;}}
    .grid{{display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:12px;}}
    .card,.offer,.pillar{{border:1px solid #e5e5e5; border-radius:12px; padding:14px;}}
    .btn{{display:inline-block; padding:10px 12px; border-radius:10px; border:1px solid #111; text-decoration:none; color:#111; margin-top:10px;}}
    h2{{margin:18px 0 10px;}}
    footer{{opacity:.6; font-size:12px; padding-top:18px;}}
  </style>
</head>
<body>
  <div class="wrap">
    {_nav(pages)}
    {''.join(sections_html)}
    <footer>Generated by compiler_latest_with_governance • v{escape(str(doc.get("schema_version","3.2")))}</footer>
  </div>
</body>
</html>
""".strip()
